
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const FILTER_SELECTED="FILTER_SELECTED";
export const SEARCH_SELECTED="SEARCH_SELECTED";
export const PAGINATION="PAGINATION";
export const SET_DATA="SET_DATA";
